Repository gear-tech/gear-bridges, pull requests merged in 2024-08, with the labels that each got.

#94 feat: Checkpoints relayer
  Cargo.lock
  Cargo.toml
  ethereum-common/src/utils.rs
  gear-programs/checkpoint-light-client/src/lib.rs
  gear-programs/checkpoint-light-client/src/tests/mod.rs
  gear-programs/checkpoint-light-client/src/wasm/mod.rs
  relayer/Cargo.toml
  relayer/src/ethereum_checkpoints/metrics.rs
  relayer/src/ethereum_checkpoints/mod.rs
  relayer/src/ethereum_checkpoints/replay_back.rs
  relayer/src/ethereum_checkpoints/sync_update.rs
  relayer/src/ethereum_checkpoints/tests/mod.rs
  relayer/src/ethereum_checkpoints/tests/sepolia-finality-update-5_254_112.json
  relayer/src/ethereum_checkpoints/tests/sepolia-finality-update-5_263_072.json
  relayer/src/ethereum_checkpoints/utils/mod.rs
  relayer/src/ethereum_checkpoints/utils/slots_batch.rs
  relayer/src/main.rs
Labels: feature

#98 refactor: Add GetState request
  gear-programs/checkpoint-light-client/io/src/lib.rs
  gear-programs/checkpoint-light-client/io/src/meta.rs
  gear-programs/checkpoint-light-client/io/src/sync_update.rs
  gear-programs/checkpoint-light-client/src/wasm/mod.rs
  gear-programs/checkpoint-light-client/src/wasm/sync_update.rs
  gear-programs/checkpoint-light-client/src/wasm/utils.rs
  relayer/src/ethereum_checkpoints/mod.rs
Labels: refactoring

#99 refactor: Change replay back mechanism
  Cargo.lock
  gear-programs/checkpoint-light-client/Cargo.toml
  relayer/src/ethereum_checkpoints/mod.rs
  relayer/src/ethereum_checkpoints/replay_back.rs
  relayer/src/ethereum_checkpoints/sync_update.rs
Labels: stability, refactoring

#101 feat: Add merkle patricia trie to ethereum-common
  Cargo.lock
  Cargo.toml
  ethereum-common/Cargo.toml
  ethereum-common/src/beacon/tests.rs
  ethereum-common/src/keccak_hasher.rs
  ethereum-common/src/lib.rs
  ethereum-common/src/memory_db.rs
  ethereum-common/src/patricia_trie.rs
  ethereum-common/src/rlp_node_codec.rs
  ethereum-common/src/utils.rs
Labels: feature

#102 refactor(relayer): Store genesis config in `.toml` file
  .gitignore
  Cargo.lock
  Cargo.toml
  gear-rpc-client/Cargo.toml
  gear-rpc-client/src/dto.rs
  gear-rpc-client/src/lib.rs
  prover/Cargo.toml
  prover/src/final_proof/mod.rs
  prover/src/latest_validator_set/mod.rs
  prover/src/lib.rs
  relayer/Cargo.toml
  relayer/src/genesis_config.rs
  relayer/src/main.rs
  relayer/src/prover_interface.rs
  relayer/src/relay_merkle_roots.rs
Labels: feature, refactoring

#103 refactor(relayer, ethereum-client): A bunch of small refactorings to `relayer` and `ethereum-client`
  ethereum/client/src/error.rs
  ethereum/client/src/lib.rs
  ethereum/client/src/tests.rs
  gear-rpc-client/src/lib.rs
  relayer/src/proof_storage/gear.rs
  relayer/src/relay_merkle_roots.rs
Labels: refactoring

#108 refactor: Add light versions of some entities
  ethereum-common/src/base_types/fixed_array.rs
  ethereum-common/src/base_types/list.rs
  ethereum-common/src/beacon/block.rs
  ethereum-common/src/beacon/block_body.rs
  ethereum-common/src/beacon/block_header.rs
  ethereum-common/src/beacon/common.rs
  ethereum-common/src/beacon/execution_payload.rs
  ethereum-common/src/beacon/light.rs
  ethereum-common/src/beacon/mod.rs
  gear-programs/checkpoint-light-client/io/src/lib.rs
Labels: refactoring

#109 refactor(relayer, ethereum contracts): Refactorings in relayer and ethereum contracts
  ethereum/src/ERC20Treasury.sol
  relayer/src/main.rs
  relayer/src/relay_merkle_roots.rs
Labels: refactoring

#111 audit: Fixes of issues found during `ethernal` audit
  circuits/plonky2_ecdsa/src/gadgets/biguint.rs
  circuits/plonky2_ed25519/Cargo.toml
  circuits/plonky2_ed25519/src/curve/curve_adds.rs
  circuits/plonky2_ed25519/src/curve/curve_types.rs
  circuits/plonky2_ed25519/src/curve/ed25519.rs
  circuits/plonky2_ed25519/src/field/ed25519_base.rs
  circuits/plonky2_ed25519/src/field/ed25519_scalar.rs
  circuits/plonky2_ed25519/src/gadgets/curve.rs
  circuits/plonky2_ed25519/src/gadgets/curve_fixed_base.rs
  circuits/plonky2_ed25519/src/gadgets/curve_windowed_mul.rs
  circuits/plonky2_ed25519/src/gadgets/curve_windowed_mul_mt.rs
  circuits/plonky2_ed25519/src/gadgets/eddsa.rs
  circuits/plonky2_ed25519/src/gadgets/nonnative.rs
  prover/src/block_finality/mod.rs
  prover/src/common/mod.rs
  prover/src/storage_inclusion/storage_trie_proof/node_parser/leaf_parser/inlined_data_parser.rs
  prover/src/storage_inclusion/storage_trie_proof/node_parser/leaf_parser/mod.rs
  prover/src/storage_inclusion/storage_trie_proof/node_parser/nibble_parser.rs
Labels: bugfix, stability, refactoring
