Repository gear-tech/gear-bridges, pull requests merged in 2024-09, with the labels that each got.

#117 refactor(message relayer): Split message relayer into reusable parts
  Cargo.lock
  gear-rpc-client/src/dto.rs
  relayer/Cargo.toml
  relayer/src/main.rs
  relayer/src/message_relayer/all_token_transfers.rs
  relayer/src/message_relayer/common/ethereum_block_listener.rs
  relayer/src/message_relayer/common/ethereum_message_sender/era.rs
  relayer/src/message_relayer/common/ethereum_message_sender/mod.rs
  relayer/src/message_relayer/common/gear_block_listener.rs
  relayer/src/message_relayer/common/merkle_root_extractor.rs
  relayer/src/message_relayer/common/message_paid_event_extractor.rs
  relayer/src/message_relayer/common/message_queued_event_extractor.rs
  relayer/src/message_relayer/common/mod.rs
  relayer/src/message_relayer/common/paid_messages_filter.rs
  relayer/src/message_relayer/event_listener.rs
  relayer/src/message_relayer/message_processor.rs
  relayer/src/message_relayer/mod.rs
  relayer/src/message_relayer/paid_token_transfers.rs
Labels: refactoring

#120 refactor(message relayer): Use `sails`-generated client to decode `bridging-payment` events
  Cargo.lock
  Cargo.toml
  gear-rpc-client/src/lib.rs
  relayer/Cargo.toml
  relayer/build.rs
  relayer/src/message_relayer/common/message_paid_event_extractor.rs
  relayer/src/message_relayer/common/paid_messages_filter.rs
Labels: refactoring

#134 feat(bridging-payment): remove token transfer to self
  gear-programs/bridging-payment/build.rs
  gear-programs/bridging-payment/src/services/error.rs
  gear-programs/bridging-payment/src/services/mod.rs
  gear-programs/bridging-payment/src/services/msg_tracker.rs
  gear-programs/bridging-payment/src/services/token_msg.rs
  gear-programs/bridging-payment/src/services/utils.rs
  gear-programs/bridging-payment/src/services/vft.rs
  gear-programs/bridging-payment/src/services/vft_gateway_msg.rs
  gear-programs/bridging-payment/src/wasm/bridging-payment.idl
  gear-programs/bridging-payment/src/wasm/tests/bridging_payment.rs
  gear-programs/bridging-payment/src/wasm/tests/utils.rs
  gear-programs/vft-gateway/src/services/mod.rs
  gear-programs/vft-gateway/src/wasm/vft-gateway.idl
Labels: feature

#133 refactor(vft-gateway): Remove Vara address from MintTokens service/message
  gear-programs/vft-gateway/src/services/error.rs
  gear-programs/vft-gateway/src/services/mod.rs
  gear-programs/vft-gateway/src/wasm/tests/utils.rs
  gear-programs/vft-gateway/src/wasm/tests/vft_gateway.rs
  gear-programs/vft-gateway/src/wasm/vft-gateway.idl
Labels: refactoring

#139 fix: Temporary pin gear-wasm-instrument until we update to 1.6.0
  Cargo.lock
  Cargo.toml
  gear-programs/bridging-payment/Cargo.toml
  gear-programs/checkpoint-light-client/Cargo.toml
  gear-programs/proof-storage/Cargo.toml
  gear-programs/vft-gateway/Cargo.toml
  gear-programs/vft-treasury/Cargo.toml
Labels: stability

#141 refactor(gear-programs): simplify bridging-payment
  gear-programs/bridging-payment-vara-supply/src/services/error.rs
  gear-programs/bridging-payment/src/lib.rs
  gear-programs/bridging-payment/src/services/error.rs
  gear-programs/bridging-payment/src/services/mod.rs
  gear-programs/bridging-payment/src/services/msg_tracker.rs
  gear-programs/bridging-payment/src/services/utils.rs
  gear-programs/bridging-payment/src/services/vft_gateway_msg.rs
  gear-programs/bridging-payment/src/wasm/bridging-payment.idl
  gear-programs/bridging-payment/src/wasm/tests/bridging_payment.rs
  gear-programs/bridging-payment/src/wasm/tests/utils.rs
Labels: refactoring

#147 refactor(vft-gateway): Set eth_client to admin by default and add update_eth_client method
  gear-programs/vft-gateway/src/services/mod.rs
  gear-programs/vft-gateway/src/wasm/tests/utils.rs
  gear-programs/vft-gateway/src/wasm/tests/vft_gateway.rs
  gear-programs/vft-gateway/src/wasm/vft-gateway.idl
Labels: refactoring

#116 feat(gear-programs): Erc20 relay program
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  ethereum-common/src/lib.rs
  ethereum-common/src/utils.rs
  gear-programs/checkpoint-light-client/Cargo.toml
  gear-programs/erc20-relay/Cargo.toml
  gear-programs/erc20-relay/README.md
  gear-programs/erc20-relay/app/Cargo.toml
  gear-programs/erc20-relay/app/build.rs
  gear-programs/erc20-relay/app/src/ERC20Treasury.json
  gear-programs/erc20-relay/app/src/abi.rs
  gear-programs/erc20-relay/app/src/error.rs
  gear-programs/erc20-relay/app/src/lib.rs
  gear-programs/erc20-relay/app/src/service.rs
  gear-programs/erc20-relay/app/tests/gclient.rs
  gear-programs/erc20-relay/build.rs
  gear-programs/erc20-relay/client/Cargo.toml
  gear-programs/erc20-relay/client/build.rs
  gear-programs/erc20-relay/client/src/lib.rs
  gear-programs/erc20-relay/src/lib.rs
Labels: feature
