Repository gear-tech/gear-bridges, pull requests merged in 2024-10, with the labels that each got.

#112 feat(relayer): Relay erc20 tokens
  Cargo.lock
  relayer/Cargo.toml
  relayer/src/erc20/mod.rs
  relayer/src/ethereum_checkpoints/mod.rs
  relayer/src/ethereum_checkpoints/replay_back.rs
  relayer/src/ethereum_checkpoints/utils/mod.rs
  relayer/src/main.rs
Labels: feature

#149 refactor(erc20-relay): Add various getters
  gear-programs/erc20-relay/app/src/lib.rs
  gear-programs/erc20-relay/app/src/service.rs
  gear-programs/erc20-relay/app/tests/gclient.rs
Labels: refactoring

#156 refactor(erc20-relay): Set external types
  Cargo.lock
  ethereum-common/src/base_types/byte_list.rs
  ethereum-common/src/base_types/bytes_fixed.rs
  ethereum-common/src/base_types/fixed_array.rs
  ethereum-common/src/beacon/block.rs
  ethereum-common/src/beacon/block_body.rs
  ethereum-common/src/beacon/block_header.rs
  ethereum-common/src/beacon/common.rs
  ethereum-common/src/beacon/execution_payload.rs
  ethereum-common/src/beacon/light.rs
  ethereum-common/src/lib.rs
  gear-programs/erc20-relay/client/Cargo.toml
  gear-programs/erc20-relay/client/build.rs
  relayer/src/erc20/mod.rs
Labels: refactoring, optimization

#158 refactor(erc20-relay): Extend `Relayed` event
  gear-programs/erc20-relay/app/src/lib.rs
  gear-programs/erc20-relay/app/src/service.rs
  gear-programs/erc20-relay/app/tests/gclient.rs
Labels: refactoring

#160 refactor: Move some entities to ethereum-common
  Cargo.lock
  ethereum-common/Cargo.toml
  ethereum-common/src/lib.rs
  ethereum-common/src/utils.rs
  relayer/src/erc20/mod.rs
  relayer/src/ethereum_checkpoints/mod.rs
  relayer/src/ethereum_checkpoints/tests/mod.rs
  relayer/src/ethereum_checkpoints/utils/mod.rs
Labels: refactoring

#155 refactor: Simplify deployment process
  .dockerignore
  Cargo.lock
  Cargo.toml
  Dockerfile
  ethereum/script/Deploy.s.sol
  ethereum/script/DeployERC20.s.sol
  ethereum/script/UpdateTreasury.s.sol
  ethereum/src/libraries/PlonkVerifier.sol
  ethereum/src/mocks/ERC20Mock.sol
  tools/deploy-to-gear/Cargo.toml
  tools/deploy-to-gear/src/main.rs
Labels: bugfix, refactoring, ethereum-contracts

#165 refactor(relayer): Use formatted timed log-builder
  relayer/src/main.rs
Labels: refactoring, relayer

#167 feat: Add CD
  .github/workflows/cd.yml
  Dockerfile
Labels: feature

#170 fix(CD): Fix gchr.io authorization in `cd.yml`
  .github/workflows/cd.yml
Labels: bugfix

#166 chore: Update to gear v1.6.2
  Cargo.lock
  Cargo.toml
  gear-programs/bridging-payment-vara-supply/app/src/services/mod.rs
  gear-programs/bridging-payment-vara-supply/tests/gtest.rs
  gear-programs/bridging-payment/app/Cargo.toml
  gear-programs/bridging-payment/app/src/services/mod.rs
  gear-programs/bridging-payment/tests/gtest.rs
  gear-programs/checkpoint-light-client/Cargo.toml
  gear-programs/checkpoint-light-client/build.rs
  gear-programs/erc20-relay/app/Cargo.toml
  gear-programs/erc20-relay/app/tests/gclient.rs
  gear-programs/proof-storage/Cargo.toml
  gear-programs/vft-gateway/app/Cargo.toml
  gear-programs/vft-gateway/tests/gtest.rs
  gear-programs/vft-treasury/app/Cargo.toml
  gear-programs/vft-treasury/tests/gtest.rs
  gear-rpc-client/src/lib.rs
Labels: stability, refactoring

#173 feat(ethereum contracts): add emergency stop for relayer contract
  ethereum/client/src/abi.rs
  ethereum/src/Relayer.sol
  ethereum/src/interfaces/IRelayer.sol
  ethereum/test/MessageQueue.t.sol
Labels: feature

#176 refactor: Parse ERC20Treasury receipt on the vft-gateway side
  Cargo.lock
  gear-programs/erc20-relay/app/Cargo.toml
  gear-programs/erc20-relay/app/src/error.rs
  gear-programs/erc20-relay/app/src/lib.rs
  gear-programs/erc20-relay/app/src/service.rs
  gear-programs/erc20-relay/app/tests/gclient.rs
  gear-programs/vft-gateway/Cargo.toml
  gear-programs/vft-gateway/app/Cargo.toml
  gear-programs/vft-gateway/app/src/services/ERC20Treasury.json
  gear-programs/vft-gateway/app/src/services/abi.rs
  gear-programs/vft-gateway/app/src/services/error.rs
  gear-programs/vft-gateway/app/src/services/mod.rs
  gear-programs/vft-gateway/src/wasm/vft-gateway.idl
  gear-programs/vft-gateway/tests/gtest.rs
Labels: refactoring, gear-programs

#190 refactor(vft-gateway): Remove unnecessary eth_contract_address
  gear-programs/vft-gateway/app/src/services/mod.rs
  gear-programs/vft-gateway/tests/gtest.rs
Labels: refactoring, gear-programs
