Repository gear-tech/gear-bridges, pull requests merged in 2024-07, with the labels that each got.

#85 feat(relayer, prover): Bump `pallet-gear-bridge` version
  Cargo.lock
  Cargo.toml
  ethereum/src/libraries/PlonkVerifier.sol
  gear-rpc-client/Cargo.toml
  gear-rpc-client/src/lib.rs
  relayer/src/main.rs
Labels: feature

#86 refactor(proof storage): Restore `gear` proof storage state on startup
  .gitignore
  Cargo.lock
  relayer/Cargo.toml
  relayer/src/main.rs
  relayer/src/proof_storage/gear.rs
  relayer/src/prover_interface.rs
Labels: stability

#68 feat: Checkpoint-light-client program
  Cargo.lock
  Cargo.toml
  ethereum-common/Cargo.toml
  ethereum-common/src/base_types/bits.rs
  ethereum-common/src/base_types/byte_list.rs
  ethereum-common/src/base_types/bytes_fixed.rs
  ethereum-common/src/base_types/fixed_array.rs
  ethereum-common/src/base_types/list.rs
  ethereum-common/src/beacon/block_header.rs
  ethereum-common/src/beacon/common.rs
  ethereum-common/src/lib.rs
  ethereum-common/src/merkle.rs
  ethereum-common/src/network.rs
  ethereum-common/src/utils.rs
  gear-programs/checkpoint-light-client/Cargo.toml
  gear-programs/checkpoint-light-client/build.rs
  gear-programs/checkpoint-light-client/io/Cargo.toml
  gear-programs/checkpoint-light-client/io/src/lib.rs
  gear-programs/checkpoint-light-client/io/src/meta.rs
  gear-programs/checkpoint-light-client/io/src/replay_back.rs
  gear-programs/checkpoint-light-client/io/src/sync_update.rs
  gear-programs/checkpoint-light-client/src/lib.rs
  gear-programs/checkpoint-light-client/src/tests/mod.rs
  gear-programs/checkpoint-light-client/src/tests/sepolia-finality-update-5_254_112.json
  gear-programs/checkpoint-light-client/src/wasm/committee.rs
  gear-programs/checkpoint-light-client/src/wasm/crypto.rs
  gear-programs/checkpoint-light-client/src/wasm/mod.rs
  gear-programs/checkpoint-light-client/src/wasm/replay_back.rs
  gear-programs/checkpoint-light-client/src/wasm/state.rs
  gear-programs/checkpoint-light-client/src/wasm/sync_update.rs
  gear-programs/checkpoint-light-client/src/wasm/utils.rs
Labels: feature

#92 chore: Require replaying back if there is a gap in checkpoints
  ethereum-common/src/utils.rs
  gear-programs/checkpoint-light-client/io/src/sync_update.rs
  gear-programs/checkpoint-light-client/src/tests/mod.rs
  gear-programs/checkpoint-light-client/src/tests/sepolia-finality-update-5_263_072.json
  gear-programs/checkpoint-light-client/src/wasm/sync_update.rs
Labels: refactoring

#95 chore: Introduce new module utils-prometheus
  Cargo.lock
  Cargo.toml
  relayer/Cargo.toml
  relayer/src/main.rs
  relayer/src/message_relayer/event_listener.rs
  relayer/src/message_relayer/merkle_root_listener.rs
  relayer/src/message_relayer/message_processor.rs
  relayer/src/message_relayer/mod.rs
  relayer/src/proof_storage/gear.rs
  relayer/src/prover_interface.rs
  relayer/src/relay_merkle_roots.rs
  utils-prometheus/Cargo.toml
  utils-prometheus/src/lib.rs
Labels: refactoring
